options:
  invinciblevillager: false
  inventoryname: 'Bartender Shop'
  compassname: Close Inventory
  compasslore: This will close your Inventory
  papername: Balance
  paperlore: This will check your balance!
  currencysign: $
  openmessage: '&aYou are entering the Bar!'
  chance: 40
  villagername: Bartender
  spawnsuccess: '&aYou have successfully spawned a bartender!'
  reloadsuccess: '&aYou have successfully reloaded the plugin!'
  prefix: '&4[&cVillagerBar&4]'
  cantdamage: &a Sorry, but you can't kill the Bartenders!
names:
  drink1: 'Gasoline'
  drink2: 'Tequila'
  drink3: 'Jack Daniels'
  drink4: 'Captain Morgan'
  drink5: 'Bacardi'
  drink6: 'Smirnoff'
  drink7: 'Fireball'
price:
  drink1: 1000
  drink2: 5000
  drink3: 10000
  drink4: 25000
  drink5: 50000
  drink6: 75000
  drink7: 100000