options:
  invinciblevillager: false
  inventoryname: 'Bartender Shop'
  compassname: Close Inventory
  compasslore: This will close your Inventory
  papername: Balance
  paperlore: This will check your balance!
  currencysign: $
  openmessage: '&aYou are entering the Bar!'
  chance: 40
  villagername: Bartender
  spawnsuccess: '&aYou have successfully spawned a bartender!'
  reloadsuccess: '&aYou have successfully reloaded the plugin!'
  prefix: '&4[&cVillagerBar&4]'
  cantdamage: '&aSorry, but you can not kill the Bartenders!'
drinks:
  drink1:
    name: 'Gasoline'
    price: 1000
    reward: 2000
  drink2:
    name: 'Tequila'
    price: 5000
    reward: 10000
  drink3:
    name: 'Jack Daniels'
    price: 10000
    reward: 20000
  drink4:
    name: 'Captain Morgan'
    price: 25000
    reward: 50000
  drink5:
    name: 'Bacardi'
    price: 50000
    reward: 100000
  drink6:
    name: 'Smirnoff'
    price: 75000
    reward: 150000
  drink7:
    name: 'Fireball'
    price: 100000
    reward: 200000