name: VillagerBar
version: 1.0
main: me.dapkin.drink.DrinkPlugin
depend: [Vault]
commands:
  villagerbar:
    description: Spawn a Bartender at your location!
    useage: /villagerbar
  bar:
    description: Opens up a virtual bar!
    useage: /bar
permissions:
  villagerbar.spawn:
    description: Allows player(s) to spawn a Bartender!
    default: false
  villagerbar.reload:
    description: Allows player(s) to reload the config!
    default: false
  villagerbar.virtual:
    description: Allows player(s) to access a Bartender from anywhere!
    default: false

